# GitVersion configuration for semantic versioning with conventional commits
mode: ContinuousDelivery

# Assembly versioning scheme
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag

# Commit messages that trigger version bumps
major-version-bump-message: '^(feat|fix|build|chore|ci|docs|style|refactor|perf|test)(\(.+\))?\!:\s.+|BREAKING CHANGE:'
minor-version-bump-message: '^feat(\(.+\))?:\s.+'
patch-version-bump-message: '^fix(\(.+\))?:\s.+'

# Other commit types that don't bump version
no-bump-message: '^(docs|style|refactor|perf|test|chore|ci|build)(\(.+\))?:\s.+'

# Branch configuration
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: true
    
  feature:
    regex: ^features?[/-]
    mode: ContinuousDelivery
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    
  hotfix:
    regex: ^hotfix[/-]
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false

# Ignore certain commits
ignore:
  sha: []
  commits-before: 2025-06-01T00:00:00

# Continuous deployment mode
continuous-delivery-fallback-tag: ci
tag-prefix: '[vV]'

# Commit date format
commit-date-format: yyyy-MM-dd